#!/bin/bash
trap '' 2
exec 3>&1
Update_agenda() {
	dialog --backtitle "" --title "" --infobox "Waiting" 3 11
	gcalcli calw 3 $(date +%m-%d-%Y) > ~/.config/openbox/agenda/$(date +%V)
}


#agenda 				1)Agenda_gcal;;
Agenda_gcal() {
	start=$(dialog --backtitle "" --title "" --calendar "choose start date" 4 40 2>&1 1>&3)
	end=$(dialog --backtitle "" --title "" --calendar "choose end date" 4 40 2>&1 1>&3)
	dialog --backtitle "" --title "" --infobox "Waiting" 3 11
	waiting=$(gcalcli --nocolor agenda $start $end)
	dialog --backtitle "" --title "" --msgbox "$waiting" 50 50
}

#calendar month(1)			2)Month_gcal;;
Month_gcal() {
	month=$(dialog --backtitle "" --title "" --calendar "choose end date" 4 40 2>&1 1>&3)
	dialog --backtitle "" --title "" --infobox "Waiting" 3 11
	month=$(gcalcli calm $month)
	clear
	read -p "$month"
}

#calendar in weeks			3)Week_gcal;;
Week_gcal() {
	range=$(dialog --backtitle "" --title "" --rangebox "Number of Weeks" 2 20 1 10 2>&1 1>&3)
	start=$(dialog --backtitle "" --title "" --calendar "choose start date" 4 40 2>&1 1>&3)
	dialog --backtitle "" --title "" --infobox "Waiting" 3 11
	week=$(gcalcli calw $range $start)
	clear
	read -p "$week"
}
#quick add				4)Qadd_gcal;;
Qadd_gcal() {
	qadd=$(dialog --backtitle "" --title "" --inputbox "" 7 30 2>&1 1>&3)
	gcalcli quick --calendar potterleo1233@gmail.com "$qadd"
}

#add a new detailed entry		5)Add_gcal;;
Add_gcal() {
	chernoble=$(dialog --separator '%' --backtitle "" --title "" --mixedform "some more shit" 150 150 10 \
	"Title: " 1 0 "" 1 30 35 0 0 \
	"Description" 2 0 "" 2 30 35 0 0 \
	"Where" 3 0 "" 3 30 35 0 0 \
	2>&1 1>&3)
	noble=$(echo '--title "'$chernoble | sed 's/.$/"/' | sed 's/%/" --description "/'| sed 's/%/" --where "/')
	thedate=$(dialog --date-format %m/%d/%Y --backtitle "" --title "" --calendar "Choose Event Date" 4 40 2>&1 1>&3)
	thetime=$(dialog --date-format %I:%M --backtitle "" --title "" --timebox "Time of Event: " 4 30 12 00 00 2>&1 1>&3)
	theduration=$(dialog --backtitle "" --title "" --rangebox "Duration of Event: " 4 30 0 60 1 2>&1 1>&3)
	thereminder=$(dialog --backtitle "" --title "" --rangebox "Reminder Before Event: " 4 30 0 60 1 2>&1 1>&3)
	clear
	finalform=$(echo "--calendar potterleo1233@gmail.com" $noble "--when" $thedate $thetime "--duration" $theduration "--reminder" $thereminder "add")
	yesno=$(dialog --backtitle "" --title "Acceptable Input?" --yesno "\n\n$(echo $noble)" 40 40 2>&1 1>&3)
	retvalue=$?
	if [ $retvalue = 0 ]
	then
		echo $finalform
		sleep 2s
	else
		break
	fi
}


#search entry				6)Search_gcal;;
Search_gcal() {
	searchc=$(dialog --backtitle "" --title "Search Terms" --inputbox "" 7 30 2>&1 1>&3)
	startdate=$(dialog --date-format %m/%d/%Y --backtitle "" --title "" --calendar "Choose Start Search Date" 4 40 2>&1 1>&3)
	enddate=$(dialog --date-format %m/%d/%Y --backtitle "" --title "" --calendar "Choose End Search Date" 4 40 2>&1 1>&3)
	dialog --backtitle "" --title "" --infobox "Waiting" 3 11
	results=$(gcalcli search --calendar potterleo1233@gmail.com "$searchc")
	dialog --backtitle "" --title "" --msgbox "$results" 10 30
}

#delete entries				7)Del_gcal;;
Del_gcal() {
	delc=$(dialog --backtitle "" --title "Delete Search Terms" --inputbox "" 7 30 2>&1 1>&3)
	gcalcli delete --calendar potterleo1233@gmail.com "$delc"
}

#edit an entry				8)Edit_gcal;;
Edit_gcal() {
	editc=$(dialog --backtitle "" --title "Edit Search Terms" --inputbox "" 7 30 2>&1 1>&3)
	gcalcli edit --calendar potterleo1233@gmail.com "$editc"

}

#import a csv				9)Import_gcal;;
Import_gcal() {
	dialog --backtitle "" --title "" --infobox "Waiting" 3 1
	select=$(ls ~/calendar/)
	imp=$(dialog --backtitle "" --title "File Name" --inputbox "$(echo $select)" 7 30 2>&1 1>&3)
	gcalcli import "$imp"

}


#set reminder os-command		0)Remind_gcal;;
Remind_gcal() {
	remm=$(dialog --backtitle "" --title "Minutes before" --inputbox "" 7 40 2>&1 1>&3)
	remc=$(dialog --backtitle "" --title "Os Command" --inputbox "" 7 30 2>&1 1>&3)
	gcalcli remind "$remm" "$remc"

}

#Quit - 				q)break;;
Quit_window() {
clear
break
}



TITLE="Google Calendar"
PS3='Google Calendar'
OPTIONS=( A "Agenda" M "One Month" W "Weeks" U "Add Non-detailed" C "Add Detailed" S "Search Entries" D "Delete Entry" E "Edit Entry" I "Import Calendar File" R "Set Reminder Command" Q "Quit")

while :
do
	CHOICE=$(dialog --clear	--backtitle "GOOGLE" --title "GOOGLE" --menu "" 17 30 11 "${OPTIONS[@]}" 2>&1 >/dev/tty)
	case $CHOICE in
		A)Agenda_gcal;;
		M)Month_gcal;;
		W)Week_gcal;;
		U)Qadd_gcal;Update_agenda;;
		C)Add_gcal;Update_agenda;;
		S)Search_gcal;;
		D)Del_gcal;;
		E)Edit_gcal;;
		I)Import_gcal;;
		R)Remind_gcal;;
		Q)clear;break;;
	esac
done
